Capitales = {
"Angola": "Luanda", "Allemagne": "Berlin", "Afghanistan" : "Kaboul", 
"Afrique du Sud" : "Pretoria", "Albanie" : "Tirana", "Algérie" : "Alger", "Andorre" : "Andorre-la-vieille", "Arabie Saoudite" : "Riyad",
"Argentine" : "Buenos Aires", "Arménie" : "Erevan", "Australie" : "Canberra", "Autriche" : "Vienne", "Azerbaïdjan" : "Bakou", 
"Bahamas" : "Nassau", "Barheïn" : "Manama", "Bangladesh" : "Dacca", "Barbade" : "Bridgetown", "Belgique" : "Bruxelles", "Belize" : "Belmopan",
"Bénin" : "Porto Novo", "Bouthan" : "Timphou", "Biélorussie" : "Minsk", "Birmanie" : "Naypyidaw", "Bolivie" : "Sucre", "Bosnie-Herzégovine" : "Sarajevo",
"Botswana" : "Gaborone", "Brésil" : "Brasilia", "Brunei" : "Bandar Seri Bagawan", "Bulgarie" : "Sofia", "Burkina Faso" : "Ouagadougou", 
"Burundi" : "Gitega", "Canbodge" : "Phnom Penh", "Cameroun" : "Yaoundé", "Canada" : "Ottawa", "Cap-Vert" : "Praia", "Chili" : "Santiago", 
"Chine" : "Pékin", "Chypre" : "Nicosie", "Colombie" : "Bogota", "Comores" : "Moroni", "Congo" : "Brazzavile", "Corée du Nord" : "Pyongyang",
"Corée du Sud" : "Séoul", "Costa Rica" : "San José" , "Côte d'Ivoire" : "Yamoussoukro", "Croatie" : "Zagreb", "Cuba" : "La Havane", 
"Danemark" : "Copenhague", "Djibouti" : "Djibouti", "Dominique" : "Roseau", "Egypte" : "Le Caire", "Emirats Arabes Unis" : "Ahu Dhabi",
"Equateur" : "Quito", "Erythrée" : "Asmara", "Espagne" : "Madrid", "Estonnie" : "Tallinn", "Eswatini" : "Mbabane", "Etats-Unis" : "Washington DC",
"Ethiopie" : "Addis-Abeba", "Fidji" : "Suva", "Finlande" : "Helsinki", "France" : "Paris", "Gabon" : "Libreville", "Gambie" : "Banjul", "Géorgie" : "Tbilissi",
"Ghana" : "Accra", "Grèce" : "Athènes", "Grenade" : "Saint Georde's", "Guatemala" : "Guatemala", "Guinée" : "Conakri",
"Guinée équatoriale" : "Malabo", "Guinée-Bissau" : "Bissau", "Guyana" : "Georgetown", "Haïti" : "Port-au-Prince", "Honduras" : "Tegucigalpa",
"Hongrie" : "Budapest", "Île Maurice" : "Port Louis", "Inde" : "New Delhi", "Indonésie" : "Jakarta", "Irak" : "Bagdad", "Iran" : "Téhéran",
"Irlande" : "Dublin", "Islande" : "Reykjavik", "Israël" : "Jérusalem", "Italie" : "Rome", "Jamaïque" : "Kingston", "Japon" : "Tokyo",
"Jordanie" : "Amman", "Kazakhstan" : "Noursoultan", "Kenya" : "Nairobi", "Kirghizistan" : "Bichkek", "Kiribati" : "Tarawa", "Kosovo" : "Pristina", 
"Koweït" : "Koweït", "Laos" : "Vientiane", "Lesotho" : "Maseru", "Lettonie" : "Riga", "Liban" : "Beyrouth", "Liberia" : "Monrovia",
"Libye" : "Tripoli", "Liechtenstein" : "Vaduz", "Lituanie" : "Vilnius", "Luxembourg" : "Luxembourg", "Macédoine du Nord" : "Skopje",
"Madagascar" : "Antananarivo", "Malaisie" : "Kuala Lumpur", "Maldives" : "Malé", "Malawi" : "Lilongwe", "Mali" : "Bamako",
"Malte" : "La Valette", "Maroc" : "Rabat", "Marshall" : "Majuro", "Mauritanie" : "Nouakchott", "Mexique" : "Mexico", "Micronésie" : "Palikir",
"Moldavie" : "Chisinau", "Monaco" : "Monaco", "Mongolie" : "Oulan-Bator", "Monténégro" : "Podgorica", "Mozambique" : "Maputo",
"Namibie" : "Windhoek", "Nauru" : "Yaren", "Népal" : "Katmandou", "Nicaragua" : "Managua", "Niger" : "Niamey", "Nigeria" : "Abuja",
"Norvège" : "Oslo", "Nouvelle Zélande" : "Wellington", "Oman" : "Masacate", "Ouganda" : "Kampala", "Ouzbékistan" : "Tachkent",
"Pakistan" : "Islamabad", "Palaos" : "Melekeok", "Palestine" : "Jérusalem-Est", "Panama" : "Panama", 
"Papouasie-Nouvelle-Guinée" : "Port Moresby", "Paraguay" : "Asuncion", "Pays-Bas" : "Amsterdam", "Pérou" : "Lima", 
"Philippines" : "Manille", "Pologne" : "Varsovie", "Portugal" : "Lisbionne", "Qatar" : "Doha", "Répulique Centrafricaine" : "Bangui",
"République démocratique du Congo" : "Kinshasa", "République Dominicaine" : "Saint Domingue", "République Tchèque" : "Prague",
"Roumanie" : "Bucarest", "Royaume-Uni" : "Londres", "Russie" : "Moscou", "Rwanda" : "Kigali", "St Christophe et Niévès" : "Basseterre",
"Saint Vincent et les Grenadines" : "Kingstown", "Sainte Lucie" : "Castrie", "Salomon" : "Honiara", "Salvador" : "San Salvador",
"Samoa" : "Apia", "Saint Marin" : "Saint Marin", "Sao Tomé et Principe" : "Sao Tomé", "Sénégal" : "Dakar", "Serbie" : "Belgrade",
"Seychelles" : "Victoria", "Sierra Leone" : "Freetown", "Singapour" : "Singapour", "Slovaquie" : "Bratislava", "Slovénie" : "Ljubljana",
"Somalie" : "Mogadiscio", "Soudan" : "Khartoum", "Soudan du Sud" : "Djouba", "Sri Lanka" : "Sri Jayawardenapura Kotte", "Suède" : "Stockholm",
"Suisse" : "Berne", "Suriname" : "Paramaribo", "Syrie" : "Damas", "Tadjikistan" : "Douchanbé", "Taïwan" : "Taipei", "Tanzanie" : "Dodoma",
"Tchad" : "N'Djamena", "Thaïlande" : "Bangkok", "Timor-Oriental" : "Dili", "Togo" : "Lomé", "Tonga" : "Nukualofa", 
"Trinité et Tobago" : "Port d'Espagne", "Tunisie" : "Tunis", "Turkménistan" : "Achgabat", "Turquie" : "Ankara", "Tuvalu" : "Fanafuti",
"Ukraine" : "Kiev", "Uruguay" : "Montevideo", "Vanuatu" : "Port-Vila", "Vatican" : "Vatican", "Vénézuéla" : "Caracas", "Viêt Nam" : "Hanoï",
"Yémen" : "Sanaa", "Zambie" : "Lusaka", "Zimbabwe" : "Harare"
}